import Footer from "./components/Footer";
import Header from "./components/Header";
import { getSeoSettings } from "./lib/getSeoSettings";
import { fetchLayout } from "./lib/fetchLayout"; // ✅ FIXED
import "./globals.css";
import Providers from "./providers";
import Script from "next/script";

export const metadata = {
  title: {
    default: "Wrirk",
    template: "%s | Wrirk",
  },
  description: "Generated by Wrirk",
};

export default async function RootLayout({ children }) {
  const [seo, layoutData] = await Promise.all([
    getSeoSettings(),
    fetchLayout(),
  ]);

  // ✅ SAFE EXTRACTION
  const navbar = layoutData?.data?.navbar;
  const footer = layoutData?.data?.footer;

  // ✅ OPTIONAL (dynamic pages for header)
  const dynamicPages =
    layoutData?.data?.dynamic_pages?.map((page) => ({
      title: page.title,
      slug: page.slug,
    })) || [];

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Bootstrap Icons */}
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css"
        />

        {/* SEO */}
        {seo?.google_verification && (
          <meta name="google-site-verification" content={seo.google_verification} />
        )}

        {seo?.bing_verification && (
          <meta name="msvalidate.01" content={seo.bing_verification} />
        )}

        {/* GA4 */}
        {seo?.ga4_id && (
          <>
            <Script
              src={`https://www.googletagmanager.com/gtag/js?id=${seo.ga4_id}`}
              strategy="afterInteractive"
            />
            <Script id="ga4-script" strategy="afterInteractive">
              {`
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());
                gtag('config', '${seo.ga4_id}');
              `}
            </Script>
          </>
        )}

        {/* GTM */}
        {seo?.gtm_id && (
          <Script id="gtm-script" strategy="afterInteractive">
            {`
              (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
              new Date().getTime(),event:'gtm.js'});
              var f=d.getElementsByTagName(s)[0],
              j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';
              j.async=true;
              j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;
              f.parentNode.insertBefore(j,f);
              })(window,document,'script','dataLayer','${seo.gtm_id}');
            `}
          </Script>
        )}
      </head>

      <body>
        {/* GTM noscript */}
        {seo?.gtm_id && (
          <noscript>
            <iframe
              src={`https://www.googletagmanager.com/ns.html?id=${seo.gtm_id}`}
              height="0"
              width="0"
              style={{ display: "none", visibility: "hidden" }}
            />
          </noscript>
        )}

        <Providers>
          {/* ✅ CLEAN DATA PASS */}
          <Header navbar={navbar} dynamicPages={dynamicPages} />

          {children}

          <Footer data={footer} />
        </Providers>

        {/* ✅ NON-BLOCKING */}
        <Script
          src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"
          strategy="lazyOnload"
        />
      </body>
    </html>
  );
}